# frozen_string_literal: true

# This initializer is generated by `rails generate doorkeeper:id_jag_grant:install`
# and configures the Doorkeeper Identity Assertion JWT Authorization Grant
# (ID-JAG) extension. See the ID-JAG draft for the full protocol specification.
#
# The extension supports two roles that can be enabled independently:
#
#   IdP role        — Issues ID-JAG assertions to clients.
#   Resource AS role — Redeems ID-JAG assertions for access tokens via the
#                     jwt_bearer grant flow.

Doorkeeper::IdJagGrant.configure do |config|
  # Enable these options when this Authorization Server issues ID-JAG
  # assertions. A client holding an ID-JAG presents it to a Resource AS to
  # obtain an access token.

  # This server's issuer identifier. Populates the `iss` claim on every
  # issued ID-JAG. Falls back to Doorkeeper's core `issuer` option when
  # left blank.
  # config.issuer "https://idp.example.com"

  # REQUIRED for the IdP role. Signs an ID-JAG assertion and returns the
  # compact JWT string. Receives a Claims object and a TokenExchangeContext.
  # The hook must merge the authoritative `sub` (resolved from the subject
  # token by the host application) into the payload before signing.
  # config.assertion_encoder do |_claims, _context|
  #   # Sign the claims and return a compact JWT string.
  # end

  # ID-JAG lifetime in seconds (draft §4.3.4). Default: 300.
  # config.expires_in 300

  # Optional (draft §4.3.3). Validates that the subject token's audience is
  # bound to the requesting client. Signature:
  #   (subject_token, subject_token_type, application) -> Boolean
  # where +application+ is a +Doorkeeper::Application+ record. For JWT
  # subject tokens the `aud` claim MUST match the client; for SAML
  # assertions the audience MUST match; for refresh tokens the token MUST
  # belong to the client. Return false/nil to reject with +invalid_grant+.
  #
  # config.validate_subject_token do |_subject_token, _token_type, _app|
  #   # Example: decode the subject token and verify aud matches the client.
  #   true
  # end

  # Optional (draft §4.3.3). Enforces refresh-token lifecycle policy when
  # the +subject_token_type+ is
  # urn:ietf:params:oauth:token-type:refresh_token. Signature:
  #   (subject_token, application) -> Boolean
  # where +application+ is a +Doorkeeper::Application+ record. Look up the
  # refresh token, verify it belongs to the client and is not
  # expired/revoked. Return false/nil to reject with +invalid_grant+.
  #
  # config.enforce_refresh_token_policy do |_subject_token, _app|
  #   # Example: find the token, check expiry/revocation, verify ownership.
  #   true
  # end

  # =========================================================================
  # Resource AS (Authorization Server) Role
  # =========================================================================
  # Enable these options when this server redeems ID-JAG assertions for
  # access tokens via the jwt_bearer grant flow.

  # This server's own issuer identifier. Every incoming ID-JAG must present
  # this value as its `aud` claim (draft §4.4.1). Falls back to `issuer`
  # (above) when left blank.
  # config.audience "https://rs.example.com"

  # REQUIRED. Answers whether `issuer` identifies a trusted IdP.
  # Return `true` for trusted issuers, `false` to reject.
  # config.trusted_issuer do |_issuer|
  #   # Verify the issuer against a configured set of trusted IdPs.
  # end

  # REQUIRED. Returns the verification key(s) for the given issuer/kid pair.
  # May return a PEM String, OpenSSL::PKey, JWK Hash, JWT::JWK, or an Array
  # of any of these.
  # config.issuer_key do |_issuer, _kid|
  #   # Look up the verification key for the issuer and key ID.
  #   # Example: fetch from a JWKS endpoint or a local key store.
  # end

  # REQUIRED. Resolves the local resource owner from the ID-JAG's issuer and
  # subject claims (draft §4.4.1 subject resolution). Return the resource
  # owner record, or nil to reject the grant.
  # config.resource_owner_from_assertion do |_issuer, _subject, _client|
  #   # Map the external (issuer, subject) pair to a local resource owner.
  #   # Example: User.find_by(external_id: subject, trusted_idp: issuer)
  # end

  # Clock-skew tolerance in seconds for exp/nbf/iat claim checks. Default: 60.
  # config.clock_skew 60

  # JWS signature algorithms accepted by the built-in verifier. `none` and
  # HMAC are never accepted. Default: ["RS256", "ES256", "PS256"].
  # config.allowed_algorithms ["RS256", "ES256", "PS256"]

  # ID-JAG §8.1 restricts this grant to confidential clients.
  # Set true to allow public clients (not recommended for production).
  # config.allow_public_clients false

  # Optional policy hook: `(client, resource_owner, scopes, claims) -> Boolean`.
  # Return false to reject the grant regardless of other checks.
  # Permissive by default.
  #
  # config.authorize do |client, resource_owner, scopes, claims|
  #   # Example: require a specific scope for JWT bearer grants.
  #   scopes.include?("api")
  # end

  # Optional replay-protection store. Must respond to
  # `#consume(jti, issuer, expires_at) -> Boolean` (returning true only on
  # first use of the `(issuer, jti)` pair). nil disables replay protection;
  # supplying an app-backed store is recommended.
  #
  # config.replay_store MyReplayStore.new

  # OPTIONAL: override the built-in JWT verifier. When set, replaces
  # trusted_issuer / issuer_key / allowed_algorithms / clock_skew /
  # replay_store / audience. Receives the raw assertion string and a
  # context; return a claims Hash, or nil/raise to reject. Leave nil
  # to use the built-in verifier (recommended).
  #
  # config.assertion_decoder do |assertion, context|
  #   # Custom verification and decoding logic.
  #   # Return decoded claims hash, or nil to reject.
  # end

  # Subject resolution used with the custom `assertion_decoder` path.
  # `(claims, client) -> resource_owner`. Defaults to the `sub` claim.
  # When the built-in verifier is in use, `resource_owner_from_assertion`
  # is used instead.
  #
  # config.resolve_resource_owner do |claims, client|
  #   User.find_by(external_id: claims["sub"])
  # end
end
