name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: >-
      Ruby ${{ matrix.ruby }}
    env:
      CI: true
    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ruby:
          - "3.4"
    steps:
      - name: Repo checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: latest

      - name: Run tests
        timeout-minutes: 10
        run: bundle exec rake spec
